### ISSUE TITLE
Device location not updating in HA

### ISSUE THREAD

**Issue by SurfingSpider** [editter/hassio-addons#1]
Hi First of all, thanks for taking the time to share this. I have been using life 360 for years with my nest but am very new to home assistant.

I have been trying to get it working on my Hassio setup (NOOB alert). I think it should all be working but the locations say away when we are home.

These are my options in the Addon

> {
>   "process_type": "MQTT",
>   "mqtt_host": "127.0.0.1",
>   "mqtt_port": 1883,
>   "mqtt_username": "######",
>   "mqtt_password": "######",
>   "preface": "life360",
>   "cert_file": "fullchain.pem",
>   "key_file": "privkey.pem",
>   "host_url": "https://######.duckdns.org:8081",
>   "refresh_minutes": 1,
>   "user_device_map": [],
>   "life360_user": "#####",
>   "life360_password": "######"
> }

I get this in the log section. which looks like life360 is working.

> starting version 3.2.4
> 1/31 3:03:34 pm - info: init/refresh token successful
> 1/31 3:03:34 pm - info: Configuring auto update for every 1 minutes
> 1/31 3:03:34 pm - info: Configuring server
> 1/31 3:03:34 pm - info: Listing via https
> 1/31 3:03:34 pm - info: Listening at port 8081
> 1/31 3:03:35 pm - info: MQTT Message was written to life360/location/Chris
> 1/31 3:03:35 pm - info: MQTT Message was written to life360/location/Claire
> 1/31 3:03:35 pm - info: Circle 1 of 1: Wolsey Family
> 1/31 3:03:35 pm - info: Member 1 of 2
>  Name: Chris; Data: {
>     "longitude": -2.5#####,
>     "latitude": 53.2#####,
>     "gps_accuracy": 50,
>     "battery_level": 76,
>     "is_intransit": 0,
>     "address": "Home",
>     "name": "Chris"
> } 
> 1/31 3:03:35 pm - info: Member 2 of 2
>  Name: Claire; Data: {
>     "longitude": -2.5#####,
>     "latitude": 53.2#####,
>     "gps_accuracy": 50,
>     "battery_level": 14,
>     "is_intransit": 0,
>     "address": "Home",
>     "name": "Claire"
> } 
> 1/31 3:04:35 pm - info: MQTT Message was written to life360/location/Chris
> 1/31 3:04:35 pm - info: MQTT Message was written to life360/location/Claire
> 1/31 3:05:35 pm - info: MQTT Message was written to life360/location/Chris
> 1/31 3:05:35 pm - info: MQTT Message was written to life360/location/Claire
> 1/31 3:06:44 pm - info: MQTT Message was written to life360/location/Chris
> 
> 

I have added this to my Configuration.yaml

> device_tracker:
>   - platform: mqtt_json
>     devices:
>       chrislife360: life360/location/Chris
>       clairelife360: life360/location/Claire

and this to my Known devices.yaml.....

> chrislife360:
>   track: yes
>   hide_if_away: no
>   name: Chris Location
>   
> clairelife360:
>   track: yes
>   hide_if_away: no
>   name: Claire Location

I have forwarded port 8081 on my rou1ter and if I go to "https://*****.duckdns.org:8081/webhook" I get a page saying "Webhook is visible externally".

Where am going wrong? how can I check what HA is receiving from life360? Am I correct in thinking that The users should appear as a marker on the map, and if I click on them on the home page (or check on the states page) I should get there lat and long?

**Comment by editter** [comment]
It looks like everything is configured correctly for the addon.  Do you have something configured for the zone section or the lat/lon in your root configuration?  (I think zone will be used if it has one for home instead of the one under homeassistant:)
This is what you should have somewhere in your yaml
```yaml
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
### OR
  zone:
    - name: Home
       latitude: 44.123
       longitude: -87.456
       radius: 410
       icon: mdi:account-multiple
    - name: Work
       latitude: 44.0
       longitude: -87.0
       radius: 1009   
```

HA doesn't actually use the address information I pass it, that was more for me to integrate life360 into Alexa before the life360 came out with their own skill.

**Comment by SurfingSpider** [comment]
Do you know what. It is alway the way isnt it. been banging my head again a brick wall for ages then ask for help and figure it out my self. I changed "mqtt_host": "127.0.0.1", to my actual address and it works. 

Thanks for the quick response though. you rock!

**Comment by editter** [comment]
Happy you got it working!  We've all been there :)
