### ISSUE TITLE
Poll Only Option

### ISSUE THREAD

**Issue by jeubanks** [editter/hassio-addons#2]
Can it be made to be poll only without the open port requirement?  Two reasons, one I don't like opening ports on my firewall.  Two, in my new setup it's rather complex as I'm behind a load balanced WAN.  I can work on the double NAT but a poll only option would be nice.

**Comment by editter** [comment]
@jeubanks You don't need to open a port on your router if you don't want to, the only reason would be if you wanted to use the Life360 WebHook callback that fires as you enter/leave a circle.  This was something I added to give the full functionality of the API however I have found that it is hard to align the radius of Home Assistant location and Life360's circle locations so I simply opted to increase the radius of both and, in theory it should fire by the time I get home which is the only thing that matters.

Have you noticed something not working as expected when your router port isn't opened?

**Comment by jeubanks** [comment]
I've noticed over the last several weeks Life360 not working well for me.
And I watched through a browser as well.  So nothing to do with the Hassio
integration.

No, I was asking because I recently went through an internet outage and had
to do a network overhaul and I haven't gotten everything "aligned" yet to
do port forwarding correctly.  So I would rather not open things until I'm
ready.  Any info/docs on running this in Hassbian?  Looking at moving to
use the Pi for other tasks BLE room-assistant stuff as well.

**Comment by editter** [comment]
So the port thing seems moot :) I've also noticed issues with life360 recently but my phones on its last leg so might be unrelated.

As for the hassbian thing I would recommend this component. I havent actually used it or reviewed it but it probably works for most cases (I think there are issues with multiple circles but again, no experience) 

https://github.com/skalavala/smarthome/blob/master/custom_components/sensor/life360.py

**Comment by editter** [comment]
Closing
