### ISSUE TITLE
Having an issue with life360 addon

### ISSUE THREAD

**Issue by sdrasmussen** [editter/hassio-addons#4]
Getting this message:

starting version 3.2.4
info: No previous state found, setting to defaults.
5/30 2:31:40 pm - error: Error getting initial token request. Ending process
5/30 2:31:40 pm - error:  Error: getaddrinfo EAI_AGAIN api.life360.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

I've uninstalled/reinstalled.  I know the username and password are correct.  Suggestions?

**Comment by editter** [comment]
Can you post an example of your config?

**Comment by sdrasmussen** [comment]
Oh, sorry, Eric.  I really don't know why this happened, but it started
working on its own without me changing anything.  I think I may have had
some database corruption in hassio, because I ditched the database and let
it rebuild, and that's probably what fixed it.  Thanks for responding.
Love the addon!

**Comment by editter** [comment]
Glad to hear it!

**Comment by sdrasmussen** [comment]
Eric, hate to bother you again, but I spoke too soon.  My issue is not
resolved.  I saw location in my default view of both my devices, and
thought that meant the issue was resolved.  However, it turns out the
information was old, and I still have the following error when starting the
360 addon:

starting version 3.2.4
6/5 9:30:33 am - error: Error getting initial token request. Ending process
6/5 9:30:33 am - error:  Error: getaddrinfo EAI_AGAIN api.life360.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

Here is my config of the addon:

{
  "process_type": "MQTT",
  "mqtt_host": "192.168.254.201",
  "mqtt_port": 1883,
  "mqtt_username": "<redacted>",
  "mqtt_password": "<redacted>",
  "preface": "life360",
  "cert_file": "fullchain.pem",
  "key_file": "privkey.pem",
  "host_url": "https://rasmussen.duckdns.org:8081",
  "refresh_minutes": 1,
  "user_device_map": [
    {
      "life360_name": "Stephen",
      "known_devices_name": "stephen_phone"
    }
  ],
  "life360_user": "<redacted>",
  "life360_password": "<redacted>"
}

Thanks,
Stephen

**Comment by editter** [comment]
Do you have a proxy setup on your network?  It looks like the error has to do with a DNS issue.  When you navigate to this URL in a browser do you see a purplish page with the message "nothing to see here, move along"? api.life360.com

**Comment by sdrasmussen** [comment]
Eric, I am able to get the purple message you mention and I am not running
a proxy.  However, I am not sure that this is an actual DNS issue.  I
notice that in version 0.0.12 the notes say you "added hassio api key".  Is
that something that should be configured in my setup here?  I can't find
any reference to how that change may have affected any users if at all.

Thanks,
Stephen

**Comment by editter** [comment]
That was related to the HTTP side of the addon but if you are using MQTT then you should be okay.  

Are you a developer or do you have experience using something like [Postman](https://www.getpostman.com/)?

**Comment by sdrasmussen** [comment]
Lol, no, not a developer, nor do I have any experience with Postman.  I am
a network engineer, and I can route the hell out of some packets, but
programming, let's just say I only know enough to fubar something pretty
easily.  That being said, I do follow directions pretty well.  What is on
your mind...using that tool for some sort of debugging or something?

**Comment by editter** [comment]
@sdrasmussen I sincerely apologize that I haven't gotten back to you sooner, life has gotten in the way.  Are you still having issues with this or have you moved on to bigger and better things?

**Comment by sdrasmussen** [comment]
Eric, no problem.  I do not have issues any longer, and to be honest, I can't really remember what fixed it (it has been working for several weeks).  Working just fine.  Thanks again.

**Comment by editter** [comment]
Sounds good! If you run into anything else feel free to let me know.
