### ISSUE TITLE
Add config key "refresh_seconds"

### ISSUE THREAD

**Issue by lostage** [editter/hassio-addons#6]
Thank you for creating this! I've been using it for quite a while. I find, though, I'd like the refresh to be quicker than 1 minute, probably 30 seconds or so. I see that if you put "0" for the `refresh_minutes` it works, but it refreshes way to often. I've tried 0.5 but it strips out the ".5" part.

If a `refresh_seconds` key was added, it wouldn't break existing configurations, and would allow us to set a quicker refresh for those special use-cases. It could instead replace `refresh_minutes` and if that key was provided it could just multiply it by 60 and use that for the `refresh_seconds`.

How feasible is that?

**Comment by editter** [comment]
I can make it happen.  I will change refresh_seconds to be a float instead of an int so it won't truncate the decimal.  I should be able to get that taken care of tonight.  

What version of Hassio (the operating system, not the addon) are you using?

**Comment by lostage** [comment]
Great!

I'm currently running Hassio 0.75.3.

**Comment by editter** [comment]
@lostage Are you using MQTT or HTTP for the addon?

**Comment by lostage** [comment]
I'm using MQTT for the sensors.

**Comment by lostage** [comment]
Oh right, yes, MQTT in the config

**Comment by editter** [comment]
Thank you for the info, it helped with another issue I was seeing which caused some delays.  I have added the ability to make the refresh_minutes a float value if you want it to be .5 you need to enter 0.5 as a value.

If you have any questions or something doesn't seem to be working please let me know.

**Comment by lostage** [comment]
Thanks, this is awesome, works great!

Can you think of any negative side effects of having it refresh so frequently?

**Comment by editter** [comment]
Other than unnecessary network traffic or computer processing probably not.  When I was really paying attention to it there were times that the Life360 app didn't update fast enough for me to justify less than a minute but it seems with every Android update it changes the reliability (for better or worse 😄)

**Comment by lostage** [comment]
Cool, thank you again!
